### PR TITLE
Drop librewolf

### PR DESCRIPTION
**Pull request by jtbx**
Takes ages to compress, I don't think anyone uses it anyway

### CODE REVIEW

**Comment by WewDuck** [comment]
I use Librewolf, and i believe tray does as well.

**Comment by gagero** [comment]
Maybe add an arkenfox package instead?

**Comment by jtbx** [comment]
Yeah I reckon that would work better anyway, you alright with an arkenfox package wewduck?

**Comment by gagero** [comment]
The only problem with that is making people comment out the occasional config.

**Comment by jtbx** [comment]
Alright I'll add arkenfox later but we'll keep librewolf for now

**Pull request closed without merging**
